routes/web.php
<?php

Route::get('/', 'PagesController@home')->name('home');
Route::get('/animes', 'PagesController@animes')->name('animes');
Route::get('/temporada', 'PagesController@season')->name('season');
Route::get('/dmca', 'PagesController@dmca')->name('dmca');
Route::get('/equipe', 'PagesController@dmca')->name('staff');
Route::any('/watch/{key}/{id}/{slug}', 'Controller@watch')->name('watch');


Route::get('/perfil/{name}', 'PagesController@perfil')->name('profile');

Route::group(['middleware' => ['guest']], function () {
    Route::post('/logar', 'AuthController@login')->name('login');
    Route::get('/cadastro', 'PagesController@register')->name('register');
    Route::post('/cadastro', 'AuthController@register');
});
Route::group(['middleware' => ['auth']], function () {
    Route::prefix('usuario')->name('user.')->group(function () {
        Route::post('/avatar', 'AuthController@avatar')->name('avatar');
        Route::post('/configuracoes', 'PagesController@settings')->name('settings');
        Route::post('/episode', 'Controller@setEpisode')->name('setEpisode');
        Route::get('/sair', function () {
            Auth::logout();
            Session::flush();
            return redirect('/');
        })->name('logout');
    });
});
Route::group(['middleware' => ['editor:1']], function () {
    Route::prefix('panel')->name('panel.')->group(function () {
        Route::get('/logs', 'PanelController@logs')->name('logs');
        Route::match(['get', 'post'], '/', 'PanelController@panel')->name('dashboard');
        Route::prefix('week')->name('week.')->group(function () {
            Route::get('/', 'PanelController@week')->name('default');
            Route::match(['get', 'post'], '/{week}', 'PanelController@weekEdit')->name('edit');
        });
        Route::group(['middleware' => ['editor:3']], function () {
            Route::prefix('avatar')->name('avatar.')->group(function () {
                Route::any('/', 'PanelController@avatars')->name('default');
            });
        });
        Route::prefix('animes')->name('animes.')->group(function () {
            Route::match(['get', 'post'], '/', 'PanelController@animes')->name('default');
            Route::match(['get', 'post'], '/add', 'PanelController@animesAdd')->name('add');
            Route::prefix('edit')->name('edit.')->group(function () {
                Route::match(['get', 'post'], '/{slug}', 'PanelController@editAnime')->name('default');
                Route::match(['get', 'post'], '/{slug}/season/{season}', 'PanelController@editSeason')->name('season');
                Route::match(['get', 'post'], '/{slug}/season/{season}/episode/{episode}', 'PanelController@editEpisode')->name('episode');
            });
        });
    });
});
Route::get('/{anime_slug}', 'PagesController@anime')->name('anime.default');
Route::get('/{anime_slug}/{season}/episodio-{episode}/{episode_slug}', 'PagesController@episode')->name('anime.episode');

resources/views/inc/footer.blade.php
<footer id="main-footer">

    <div id="info">
        <div class="container wrap">

            <div class="row">
                <div class="col-md-12">
                    <div class="row">
                        <div class="col-sm-12 col-md-12 col-lg-8">
                            <div class="col-md-12">
                                <div class="row">
                                    <div class="col-md-6">
                                        <div id="column">
                                            <b>Menu</b>
                                            <ul class="inline-list">
                                                <li><a dhref="">Termos de Uso</a></li>
                                                <li><a href="{{ route('dmca') }}">DMCA</a></li>
                                                <li><a dhref="">Facebook</a></li>
                                                <li><a dhref="">Contato</a></li>
                                            </ul>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div id="column">
                                            <b>Parceiros</b>
                                            <ul class="inline-list">
                                                <li><a href="http://game.micemixy.pro" target="_blank">Transformice Pirata</a></li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-12 col-md-12 col-lg-4">
                            <div class="iframe">
                                <!-- <iframe src="https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2Fzanimez&tabs=none&width=340&height=155&small_header=true&adapt_container_width=true&hide_cover=false&show_facepile=true&appId" width="100%" height="155" scrolling="no" frameborder="0" allowtransparency="true"></iframe>
                                 -->
								<img src='http://zanimes.com/images/logoz.png'/>
							</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div style="display:none">
        <script id="_waucr9">var _wau = _wau || []; _wau.push(["small", "lf9yfa1a62", "cr9"]);</script><script async src="//waust.at/s.js"></script>
    </div>
    <div id="dev">
        <div class="container wrap">
            <div class="row">
                <div class="col-md-12">
                    <div class="">
                        <p class="dev">
                            Desenvolvido com <i style="color:#C50003" class="fa fa-heart"></i> por <a href="http://thalysmarcio.com/" target="_blank">Thalys Márcio</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>

</footer>

resources/views/inc/header.blade.php
<nav class="navbar navbar-expand-md navbar-dark">
    <div class="container">
        <div class="col-12">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mobile-menu" aria-controls="mobile-menu" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse" id="mobile-menu">
                <div class="w-100">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item {{ Request::is('/') ? 'active' : 'non' }}"><a class="nav-link" href="{{ route('home') }}">@lang('pages.menu.home')</a></li>
                        <li class="{{ Request::is('animes') ? 'active' : 'non' }}"><a class="nav-link" href="{{ route('animes') }}">@lang('pages.menu.animes')</a></li>
                        <li class="{{ Request::is('temporada') ? 'active' : 'non' }}"><a class="nav-link" href="{{ route('season') }}">@lang('pages.menu.season')</a></li>
                        <li class="{{ Request::is('noticias') ? 'active' : 'non' }}"><a class="nav-link" href="{{ route('home') }}">@lang('pages.menu.articles')</a></li>
                        <li class="{{ Request::is('forum') ? 'active' : 'non' }}" ><a class="nav-link" href="{{ route('home') }}">@lang('pages.menu.forum')</a></li>
                    </ul>
                </div>
                <div class="my-2 my-lg-0">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <div class="search-content">
                                <form role="search" method="get" class="search-form">
                                    {{ csrf_field() }}
                                    <label>
                                        <span class="screen-reader-text">Procurar por:</span>
                                        <input type="search" class="search-field" placeholder="Procurar" name="procura">
                                    </label>
                                    <input type="submit" class="search-submit" value="Search">
                                </form>
                            </div>
                        </li>
                        @auth
                            <li class="nav-item">
                                <div class="dropdown">
                                    <a id="conta" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="nav-link avatar nav-link dropdown-toggle">
                                        <img src="{{ ZAnimesControl::url('avatars/default.jpg') }}" srcset="{{ Auth::user()->avatar }}" data-src="{{ Auth::user()->avatar }}" data-srcset="{{ Auth::user()->avatar }}" height="50" width="50">
                                    </a>
                                    <div class="fade dropdown-menu dropdown-menu-right account-panel" aria-labelledby="conta">
                                        @if(Auth::user()->editor)
                                            <a class="dropdown-item" href="{{ route('panel.dashboard') }}">@lang('pages.panel')</a>
                                            <div class="dropdown-divider"></div>
                                        @endif
                                        <a class="dropdown-item" href="{{ route('profile', ['name' => Auth::user()->name]) }}">{{ Auth::user()->name }}</a>
                                        <a class="dropdown-item" href="{{ route('user.settings') }}">@lang('pages.settings')</a>
                                        <a class="dropdown-item" href="{{ route('user.logout') }}">@lang('pages.logout')</a>
                                    </div>
                                </div>
                            </li>
                        @else
                            <li class="nav-item">
                                <div class="dropdown">
                                    <a id="conta" data-toggle="modal" data-target="#loginModal" class="nav-link avatar nav-link dropdown-toggle">
                                        <img src="{{ ZAnimesControl::url('avatars/default.jpg') }}" height="50" width="50">
                                    </a>
                                </div>
                            </li>
                        @endauth
                    </ul>
                </div>

            </div>
        </div>
    </div>
</nav>

@guest
<!-- Modal -->
<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">@lang('login.title')</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{ route('login') }}" method="post">
                <div class="modal-body">
                    @csrf
                    <div class="form-group">
                        <label for="email">@lang('login.email')</label>
                        <input name="email" type="email" class="form-control" id="email" placeholder="email@example.com">
                    </div>
                    <div class="form-group">
                        <label for="password">@lang('login.password')</label>
                        <input name="password"  type="password" class="form-control" id="password" placeholder="Password">
                    </div>
                </div>
                <div class="modal-footer">
                    <a href="{{ route('register') }}" class="btn btn-secondary" role="button">@lang('login.register')</a>
                    <button type="submit" class="btn btn-primary">@lang('login.submit')</button>
                </div>
            </form>
        </div>
    </div>
</div>
@endguest

resources/views/inc/panel-header.blade.php
<nav class="navbar navbar-expand-md navbar-dark">
    <div class="container">
        <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item {{ Request::is('panel') ? 'active' : 'non' }}"><a class="nav-link" href="{{ route('panel.dashboard') }}">Dashboard</a></li>
                <li class="nav-item {{ Request::is('panel/animes') ? 'active' : 'non' }}"><a class="nav-link" href="{{ route('panel.animes.default') }}">Animes</a></li>
                <li class="nav-item {{ Request::is('panel/animes/add') ? 'active' : 'non' }}"><a class="nav-link" href="{{ route('panel.animes.add') }}">Add Anime</a></li>
                <li class="nav-item {{ Request::is('panel/week') ? 'active' : 'non' }}"><a class="nav-link" href="{{ route('panel.week.default') }}">Week</a></li>
                <li class="nav-item {{ Request::is('panel/avatar') ? 'active' : 'non' }}"><a class="nav-link" href="{{ route('panel.avatar.default') }}">Avatar</a></li>
            </ul>
        </div>
    </div>
</nav>

resources/views/inc/similar_animes.blade.php
<div class="c-widget-content style-1">
    <div class="c-blog__heading style-2 font-heading">
        <h4>@lang('anime.also_liked')</h4>
    </div>
    <div class="widget-content">
        @foreach ($similar as $anime)
            <div class="popular-item-wrap">
                <a title="{{ $anime->name }}" href="{{ route('anime.default', ['anime_slug' => $anime->slug_name]) }}">
                    <div class="popular-img widget-thumbnail c-image-hover">
                        <img width="50" height="75" data-src="{{ ZAnimesControl::url('animes/' . $anime->slug_name . '/' . $anime->image) }}" data-srcset="{{ ZAnimesControl::url('animes/' . $anime->slug_name . '/' . $anime->image) }}" data-sizes="(max-width: 50px) 75vw, 50px" class="img-responsive lazyload effect-fade" alt="{{ $anime->name }}"/>
                    </div>
                    <div class="popular-content">
                        <h5 class="widget-title">
                            {{ $anime->name }}
                        </h5>
                        <div class="list-chapter">
                            <div class="chapter-item">
                                <span class="post-on font-meta">{{ $anime->author }}</span>
                                <span class="post-on font-meta">{{ $anime->year }}</span>
                                <span class="post-on font-meta count">{{ $anime->monthly_views->count() }}  <i class="fa fa-star fa-1x"></i></span>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
        @endforeach
    </div>
</div>

resources/views/inc/top_animes.blade.php
<div class="c-widget-content style-1">
    <div class="c-blog__heading style-2 font-heading">
        <h4>@lang('home.most-accesseds-in-the-month')</h4>
    </div>
    <ul id="home-toprank-list-1" class="top5" data-genre="gl">
        @foreach ($monthly as $anime)
            <li style="background-image: url({{ ZAnimesControl::url('animes/' . $anime->slug_name . '/' . $anime->image) }});">
                <a href="{{ route('anime.default', ['anime_slug' => $anime->slug_name]) }}" class="overlay">
                    <span class="iteration">{{ $loop->iteration }}</span>
                    <div class="meta">
                        <h4 class="title">{{ $anime->name }}</h4>
                        <span>{{ $anime->author }}</span>
                    </div>
                </a>
            </li>
        @endforeach
    </ul>
</div>