routes/web.php
<?php

Route::get('/', 'PagesController@home')->name('home');
Route::get('/animes', 'PagesController@animes')->name('animes');
Route::get('/temporada', 'PagesController@season')->name('season');
Route::get('/dmca', 'PagesController@dmca')->name('dmca');
Route::get('/equipe', 'PagesController@dmca')->name('staff');
Route::any('/watch/{key}/{id}/{slug}', 'Controller@watch')->name('watch');


Route::get('/perfil/{name}', 'PagesController@perfil')->name('profile');

Route::group(['middleware' => ['guest']], function () {
    Route::post('/logar', 'AuthController@login')->name('login');
    Route::get('/cadastro', 'PagesController@register')->name('register');
    Route::post('/cadastro', 'AuthController@register');
});
Route::group(['middleware' => ['auth']], function () {
    Route::prefix('usuario')->name('user.')->group(function () {
        Route::post('/avatar', 'AuthController@avatar')->name('avatar');
        Route::post('/configuracoes', 'PagesController@settings')->name('settings');
        Route::post('/episode', 'Controller@setEpisode')->name('setEpisode');
        Route::get('/sair', function () {
            Auth::logout();
            Session::flush();
            return redirect('/');
        })->name('logout');
    });
});
Route::group(['middleware' => ['editor:1']], function () {
    Route::prefix('panel')->name('panel.')->group(function () {
        Route::get('/logs', 'PanelController@logs')->name('logs');
        Route::match(['get', 'post'], '/', 'PanelController@panel')->name('dashboard');
        Route::prefix('week')->name('week.')->group(function () {
            Route::get('/', 'PanelController@week')->name('default');
            Route::match(['get', 'post'], '/{week}', 'PanelController@weekEdit')->name('edit');
        });
        Route::group(['middleware' => ['editor:3']], function () {
            Route::prefix('avatar')->name('avatar.')->group(function () {
                Route::any('/', 'PanelController@avatars')->name('default');
            });
        });
        Route::prefix('animes')->name('animes.')->group(function () {
            Route::match(['get', 'post'], '/', 'PanelController@animes')->name('default');
            Route::match(['get', 'post'], '/add', 'PanelController@animesAdd')->name('add');
            Route::prefix('edit')->name('edit.')->group(function () {
                Route::match(['get', 'post'], '/{slug}', 'PanelController@editAnime')->name('default');
                Route::match(['get', 'post'], '/{slug}/season/{season}', 'PanelController@editSeason')->name('season');
                Route::match(['get', 'post'], '/{slug}/season/{season}/episode/{episode}', 'PanelController@editEpisode')->name('episode');
            });
        });
    });
});
Route::get('/{anime_slug}', 'PagesController@anime')->name('anime.default');
Route::get('/{anime_slug}/{season}/episodio-{episode}/{episode_slug}', 'PagesController@episode')->name('anime.episode');

app/Models/Animes.php
<?php

namespace App\Models;

use DB;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Animes extends Model
{
    protected $table = 'animo_animes';

    protected $fillable = ['id', 'name', 'slug_name', 'sinopse', 'image', 'author', 'latest_episode', 'status', 'year', 'age_group', 'studio', 'user_id'];

    public function seasons() {
        return $this->hasMany('App\Models\AnimesSeasons', 'anime_id', 'id')->orderByDesc('season');
    }

    public function episodes() {
        return $this->hasMany('App\Models\AnimesSeasonsEpisodes', 'anime_id');
    }

    public function latestEpisode() {
        return $this->hasOne('App\Models\AnimesSeasonsEpisodes', 'anime_id');
    }

    public function genres() {
        return $this->belongsToMany('App\Models\Genres', 'animo_genres_animes','anime_id', 'genre_id', 'id');
    }

    public function monthly_views()
    {
        return $this->hasMany('App\Models\AnimesSeasonsEpisodesViews', 'anime_id')->where('created_at', '>=', Carbon::now()->addMonths(-1)->format('Y-m-d H:i:s'));
    }

    public function weekly_views()
    {
        return $this->hasMany('App\Models\AnimesSeasonsEpisodesViews', 'anime_id')->where('created_at', '>=', Carbon::now()->addWeeks(-1)->format('Y-m-d H:i:s'));
    }

    public function creator() {
        return $this->hasOne('App\User', 'id', 'user_id')->with('staffLog');
    }

    public function staffLog() {
        return $this->hasMany('App\Models\LogsStaff', 'user_id', 'user_id');
    }
}

app/Http/Controllers/PanelController.php
<?php
namespace App\Http\Controllers;

use App\Models\LogsStaff;
use App\Models\Week;
use App\Models\WeekAnimes;
use DB;
use Auth;
use App\User;
use App\ZAnimesControl;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Intervention\Image\Facades\Image;
use App\Models\Genres;
use App\Models\Animes;
use App\Models\AnimesSeasons;
use App\Models\AnimesSeasonsEpisodes;
use App\Models\AnimesSeasonsEpisodesViews;
use App\Services\Contracts\ZAnimesInterface;

class PanelController extends Controller {

    public function panel() {
        $analystic_users = collect();
        $analystic_views = collect();
        foreach(range(-14, 0) as $i) {
            $date = Carbon::now()->addDays($i)->format('Y-m-d H:i:s');
            $analystic_users->put($date, 0);
            $analystic_views->put($date, 0);
        }
        return view('pages.panel.panel', [
            'analystic_users' => $analystic_users->merge(AnimesSeasonsEpisodes::where('created_at', '>=', $analystic_users->keys()->first())
                ->groupBy('date')
                ->get([
                    DB::raw('DATE(created_at) as date'),
                    DB::raw('COUNT(*) as "count"')
                ])
                ->pluck('count', 'date')),
            'analystic_views' => $analystic_views->merge(AnimesSeasonsEpisodesViews::where('created_at', '>=', $analystic_views->keys()->first())
                ->groupBy('date')
                ->orderBy('date')
                ->get([
                    DB::raw('DATE(created_at) as date'),
                    DB::raw('COUNT(*) as "count"')
                ])
                ->pluck('count', 'date')),
            'genres' => Genres::get(),
            'animes' => Animes::get(),
            'seasons' => AnimesSeasons::get(),
            'episodes' => AnimesSeasonsEpisodes::get(),
            'users' => User::get()
        ]);
    }

    public function animes() {
        return view('pages.panel.animes.animes', [
            'animes' => Animes::orderByDesc('created_at')->paginate(30)
        ]);
    }

    public function avatars(Request $request) {
        if ($request->has('user_id')) {
            $user = User::where('id', $request->user_id)->first();
            if ($request->has('approve')) {
                if ($request->approve == "ok") {
                    $user->update(['avatar' => $user->avatar_pending]);
                } else {
                    $user->update(['avatar_pending' => $user->avatar]);
                }
            } else {
                $user->update(['avatar_pending' => $user->avatar]);
            }
        }
        return view('pages.panel.avatars.default', [
            'avatars' => User::orderByDesc('avatar_update')->whereRaw('avatar != avatar_pending')->paginate(30)
        ]);
    }

    public function moderateAvatar($user_id) {
        $user = User::where('id', $user_id)->firstOrFail();
        return view('pages.panel.avatars.moderate', [
            'user' => $user
        ]);
    }

    public function week() {
        return view('pages.panel.week', [
            'weeks' => Week::all()
        ]);
    }

    public function weekEdit(Request $request, $id_week) {
        $week = Week::findOrFail($id_week);
        if ($request->has('id') && $request->has('action')) {
            $_query = Animes::where('id', $request->id);
            if ($_query->doesntExist()) {
                return redirect('/panel/week/' . $id_week)->with('warning', 'The anime with id \'' . $request->id . '\'. doesn\'t exists');
            }
            if (optional($_query->first())->status != 0) {
                return redirect('/panel/week/' . $id_week)->with('warning', 'The anime with id \'' . $request->id . '\'. isn\'t Ongoing');
            }
            if ($request->action == "Add" && $request->has('hour')) {
                if ($week->animes()->where(['week_id' => $id_week, 'anime_id' => $request->id])->exists()) {
                    return redirect('/panel/week/' . $id_week)->with('warning', 'The anime with id \'' . $request->id . '\'. exists');
                }
                $week->animes()->create(['week_id' => $id_week, 'anime_id' => $request->id, 'hour' => $request->hour]);
            } else {
                if ($week->animes()->where(['week_id' => $id_week, 'anime_id' => $request->id])->doesntExist()) {
                    return redirect('/panel/week/' . $id_week)->with('warning', 'The anime with id \'' . $request->id . '\'. doesn\'t exists');
                }
                $week->animes()->where(['week_id' => $id_week, 'anime_id' => $request->id])->forceDelete();
            }
        }
        return view('pages.panel.week.edit', [
            'week' => $week
        ]);
    }

    public function logs() {
        return view('pages.panel.logs', [
            'logs' => LogsStaff::orderByDesc('created_at')->paginate(30)
        ]);
    }

    public function animesAdd(Request $request)
    {
        if ($request->has('name') && $request->has('author') && $request->has('year') && $request->has('status') && $request->has('sinopse') && $request->has('genre') && $request->hasFile('image')) {
            $request->validate([
                'name' => 'required|max:255',
                'author' => 'required|max:255',
                'year' => 'integer',
                'age_group' => 'integer',
                'status' => 'required',
                'sinopse' => 'required',
                'genre' => 'required',
                'image' => 'required'
            ]);
            $slug = str_slug($request->input('name'), '-');
            if (Animes::where('slug_name', $slug)->doesntExist()) {
                $anime = new Animes([
                    'name' => $request->input('name'),
                    'slug_name' => $slug,
                    'sinopse' => $request->input('sinopse'),
                    'image' => "cover.jpg?t=" . str_random(20) . time(),
                    'author' => $request->input('author'),
                    'status' => $request->input('status'),
                    'year' => $request->input('year'),
                    'age_group' => $request->input('age_group'),
                    'studio' => $request->input('studio'),
                    'user_id' => Auth::user()->id
                ]);
                if ($anime->save()) {
                    ZAnimesControl::put("animes/" . $anime->slug_name . "/cover.jpg", Image::make($request->file('image')->getRealPath())->resize(340, 510)->encode('jpg', 80));
                    $anime->staffLog()->save(new LogsStaff(['user_id' => optional(Auth::user())->id, 'message' => 'Has added the anime ' . $anime->id]));
                    $anime->genres()->sync($request->input('genre'));
                    return redirect()->route('panel.animes.edit.default', ['slug' => $anime->slug_name]);
                } else {
                    return redirect('/panel/animes/add')->with('danger', 'Can\'t add \'' . $anime->name . '\'.');
                }
            }
            return redirect('/panel/animes/add')->with('warning', 'The anime with slug \'' . $slug . '\'. exists');
        }
        return view('pages.panel.animes.add', [
            'genres' => Genres::get()
        ]);
    }

    public function editAnime(Request $request, $slug) {
        $anime = Animes::where('slug_name', $slug)->firstOrFail();
        if (Auth::user()->editor <= 1 && $anime->user_id != Auth::user()->id) {
            return view('pages.panel.not-have-permission', [
                'anime' => $anime
            ]);
        }
        if ($request->has('delete')) {
            $anime->episodes()->delete();
            $anime->seasons()->delete();
            $anime->delete();
            ZAnimesControl::deleteDirectory('animes/' . $slug);
            $anime->staffLog()->save(new LogsStaff(['user_id' => optional(Auth::user())->id, 'message' => 'Has deleted the anime ' . $anime->id]));
            return redirect()->route('panel-animes', ['slug' => $anime->slug_name])->with('success', 'Anime \'' . $anime->name . '\' deleted.');
        } else if ($request->has('name') && $request->has('author') && $request->has('year') && $request->has('status') && $request->has('sinopse')) {
            $request->validate([
                'name' => 'required|max:255',
                'author' => 'required|max:255',
                'year' => 'integer',
                'studio' => 'required',
                'age_group' => 'integer',
                'status' => 'required',
                'sinopse' => 'required',
                'genre' => 'required',
            ]);
            $anime->name = $request->input('name');
            $anime->author = $request->input('author');
            $anime->year = $request->input('year');
            $anime->studio = $request->input('studio');
            $anime->age_group = $request->input('age_group');
            if ($request->has('genre')) {
                $anime->genres()->sync($request->input('genre'));
            }
            $anime->status = $request->input('status');
            $anime->sinopse = $request->input('sinopse');
            if ($request->hasFile('image'))
            {
                $anime->image = "cover.jpg?t=" . str_random(20) . time();
                ZAnimesControl::put("animes/" . $anime->slug_name . "/cover.jpg", Image::make($request->file('image')->getRealPath())->resize(340, 510)->encode('jpg', 80));
            }
            if ($anime->save()) {
                $anime->staffLog()->save(new LogsStaff(['user_id' => optional(Auth::user())->id, 'message' => 'Has edited the anime ' . $anime->id]));
                return redirect()->route('panel.animes.edit.default', ['slug' => $anime->slug_name])->with('success', '\'' . $anime->name . '\' edited.');
            }
        } else if ($request->has('title') && $request->has('season')) {
            $request->validate([
                'title' => 'required|max:255',
                'season' => 'integer'
            ]);

resources/views/pages/panel/animes/animes.blade.php
@extends('layouts.panel')

@section('title', "Animes")

@section('container')
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">Animes</div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Name</th>
                            <th>Seasons</th>
                            <th>Episodes</th>
                            <th>Author</th>
                            <th>Created</th>
                            <th>Updated</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach ($animes as $anime)
                            <tr>
                                <td>{{ $anime->id }}</td>
                                <td>{{ $anime->name }}</td>
                                <td>{{ $anime->seasons()->count() }}</td>
                                <td>{{ $anime->episodes()->count() }}</td>
                                <td>{{ $anime->creator->name }}</td>
                                <td>{{ $anime->created_at }}</td>
                                <td>{{ $anime->updated_at }}</td>
                                <td style="width: 105px;text-align: center;"><a href="{{ route('panel.animes.edit.default', array('slug' => $anime->slug_name)) }}"><button type="button" class="btn btn-default">Edit</button></a></td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
                {{$animes->links()}}
            </div>
        </div>
    </div>
@stop

resources/views/pages/panel/animes/edit.blade.php
@extends('layouts.panel')

@section('title', "Edit Anime")

@section('container')
    @if (session('success'))
        <div class="col-md-12">
            <div class="alert alert-success" role="success">
                {{ session('success') }}
            </div>
        </div>
    @endif
    <div class="col-md-12">
        <div class="card">
            <form role="form" method="post" enctype="multipart/form-data">
                {{ csrf_field() }}
                <div class="card-header">
                    Edit Anime
                </div>
                <div class="card-body">
                    <div class=col-md-12">
                        <div class="row">
                            <div class="col-md-8">
                                <div class="form-group">
                                    <label>Name</label>
                                    <input name="name" class="form-control" value="{{ $anime->name }}">
                                </div>
                                <div class="form-group">
                                    <label>Author</label>
                                    <input name="author" class="form-control" value="{{ $anime->author }}">
                                </div>
                                <div class="form-group">
                                    <label>Year</label>
                                    <input name="year" class="form-control" value="{{ $anime->year }}">
                                </div>
                                <div class="form-group">
                                    <label>Studio</label>
                                    <input name="studio" class="form-control" value="{{ $anime->studio }}">
                                </div>
                                <div class="form-group">
                                    <label>Age Group</label>
                                    <select name="age_group" class="form-control-lg">
                                        <option value="0" @if($anime->age_group == 0) selected @endif>L</option>
                                        <option value="10" @if($anime->age_group == 10) selected @endif>10</option>
                                        <option value="12" @if($anime->age_group == 12) selected @endif>12</option>
                                        <option value="14" @if($anime->age_group == 14) selected @endif>14</option>
                                        <option value="16" @if($anime->age_group == 16) selected @endif>16</option>
                                        <option value="18" @if($anime->age_group == 18) selected @endif>18</option>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label for="status">Status</label>
                                    <select name="status" class="form-control-lg">
                                        <option value="0" @if($anime->status == 0) selected @endif>Ongoing</option>
                                        <option value="1" @if($anime->status == 1) selected @endif>Completed</option>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label for="sinopse">Sinopse</label>
                                    <textarea name="sinopse" rows="7" class="form-control">{{ $anime->sinopse }}</textarea>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>
                                        <div class="anime">
                                            <div class="poster">
                                                <img data-src="{{ ZAnimesControl::url('animes/' . $anime->slug_name . '/' . $anime->image) }}" data-srcset="{{ ZAnimesControl::url('animes/' . $anime->slug_name . '/' . $anime->image) }}" data-sizes="(max-width: 125px) 100vw, 125px" class="img-responsive effect-fade lazyloaded" src="{{ ZAnimesControl::url('animes/' . $anime->slug_name . '/' . $anime->image) }}" style="padding-top:180px; " alt="as54sa6 dfg df" sizes="(max-width: 125px) 100vw, 125px" srcset="{{ ZAnimesControl::url('animes/' . $anime->slug_name . '/' . $anime->image) }}">
                                            </div>
                                        </div>
                                    </label>
                                    <input name="image" type="file" >
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <div class="row">
                            <div class="form-group">
                                <div class="form-group checkbox-group row">
                                    @foreach ($genres as $genre)
                                        <div class="checkbox col-md-3 ">
                                            <input id="{{ $genre->id }}" name="genre[{{ $genre->id }}]" value="{{ $genre->id }}" type="checkbox" @if( $anime->genres()->get()->contains($genre->id) ) checked @endif>
                                            <label for="{{ $genre->id }}"> {{ $genre->name }} </label>
                                        </div>
                                    @endforeach
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="checkbox">
                                    <input id="delete" name="delete" value="delete" type="checkbox">
                                    <label for="delete"> Delete </label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <div class="form-group">
                        <button type="submit" class="btn btn-default">Edit</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="col-md-12">
        <div class="card">
            <form method="POST" enctype="multipart/form-data">
                {{ csrf_field() }}
                <div class="card-header">
                    Add Season
                </div>
                <div class="card-body">
                    <div class="form-group">
                        <label for="title">Title</label>
                        <input type="text" class="form-control" name="title" placeholder="1º Season">
                    </div>
                    <div class="form-group">
                        <label for="season">Season nº</label>
                        <input type="text" class="form-control" name="season" placeholder="1">
                    </div>
                </div>
                <div class="card-footer">
                    <div class="form-group">
                        <button type="submit" class="btn btn-default">Add</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                Seasons
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>Temporada</th>
                            <th>Nome</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach ($anime->seasons as $season)
                            <tr>
                                <td>{{ $season->season }}</td>
                                <td>{{ $season->title }}</td>
                                <td style="width: 105px;text-align: center;"><a href="{{ route('panel.animes.edit.season', array('slug' => $anime->slug_name, 'season' => $season->season)) }}"><button type="button" class="btn btn-default">Editar</button></a></td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/pages/panel/animes/season.blade.php
@extends('layouts.panel')

@section('title', "Edit Season")

@section('container')
    <div class="col-md-12">
        @if (session('success'))
            <div class="alert alert-success" role="success">
                {{ session('success') }}
            </div>
        @endif
        @if (session('warning'))
            <div class="alert alert-warning" role="warning">
                {{ session('warning') }}
            </div>
        @endif
    </div>
    <div class="col-md-12">
        <div class="card">
            <form method="POST" enctype="multipart/form-data">
                {{ csrf_field() }}
                <div class="card-header">
                    Anime: '{{ $anime->name }}', Season: '{{ $season->title }}'
                </div>
                <div class="card-body">
                    <div class="form-group">
                        <label for="title">Title</label>
                        <input type="text" class="form-control" name="name" value="{{ $season->title  }}">
                    </div>
                    <div class="form-group">
                        <div class="checkbox">
                            <input id="delete" name="delete" value="delete" type="checkbox">
                            <label for="delete"> Delete </label>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-default">Edit</button>
                </div>
            </form>
        </div>
    </div>
    <div class="col-md-12">
        <div class="card">
            <form name="edit" method="POST" enctype="multipart/form-data">
                {{ csrf_field() }}
                <div class="card-header">Add Episode</div>
                <div class="card-body">
                    <div class="form-group">
                        <label for="title">Title</label>
                        <input type="text" class="form-control" name="title">
                    </div>
                    <div class="form-group">
                        <label for="episode">Sinopse</label>
                        <input type="text" class="form-control" name="prev">
                    </div>
                    <div class="form-group">
                        <label for="episode">Episode</label>
                        <input type="text" class="form-control" name="episode">
                    </div>
                    <div class="form-group">
                        <label for="video">Video</label>
                        <input type="text" class="form-control" name="video">
                    </div>
                    <div class="form-group">
                        <label for="poster">Poster ( 640x360 )</label>
                        <input type="text" class="form-control" name="poster" value="">
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-default">Add</button>
                </div>
            </form>
        </div>
    </div>
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">Episodes</div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Episode</th>
                            <th>Title</th>
                            <th>Created</th>
                            <th>Updated</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach ($episodes as $episode)
                            <tr>
                                <td>{{ $episode->id }}</td>
                                <td>{{ $episode->episode }}</td>
                                <td>{{ $episode->title }}</td>
                                <td>{{ $episode->created_at }}</td>
                                <td>{{ $episode->updated_at }}</td>
                                <td style="width: 105px;text-align: center;"><a href="{{ route('panel.animes.edit.episode', array('slug' => $anime->slug_name, 'season' => $season->season, 'episode' => $episode->episode)) }}"><button type="button" class="btn btn-default">Edit</button></a></td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@stop