routes/web.php
<?php

Route::get('/', 'PagesController@home')->name('home');
Route::get('/animes', 'PagesController@animes')->name('animes');
Route::get('/temporada', 'PagesController@season')->name('season');
Route::get('/dmca', 'PagesController@dmca')->name('dmca');
Route::get('/equipe', 'PagesController@dmca')->name('staff');
Route::any('/watch/{key}/{id}/{slug}', 'Controller@watch')->name('watch');


Route::get('/perfil/{name}', 'PagesController@perfil')->name('profile');

Route::group(['middleware' => ['guest']], function () {
    Route::post('/logar', 'AuthController@login')->name('login');
    Route::get('/cadastro', 'PagesController@register')->name('register');
    Route::post('/cadastro', 'AuthController@register');
});
Route::group(['middleware' => ['auth']], function () {
    Route::prefix('usuario')->name('user.')->group(function () {
        Route::post('/avatar', 'AuthController@avatar')->name('avatar');
        Route::post('/configuracoes', 'PagesController@settings')->name('settings');
        Route::post('/episode', 'Controller@setEpisode')->name('setEpisode');
        Route::get('/sair', function () {
            Auth::logout();
            Session::flush();
            return redirect('/');
        })->name('logout');
    });
});
Route::group(['middleware' => ['editor:1']], function () {
    Route::prefix('panel')->name('panel.')->group(function () {
        Route::get('/logs', 'PanelController@logs')->name('logs');
        Route::match(['get', 'post'], '/', 'PanelController@panel')->name('dashboard');
        Route::prefix('week')->name('week.')->group(function () {
            Route::get('/', 'PanelController@week')->name('default');
            Route::match(['get', 'post'], '/{week}', 'PanelController@weekEdit')->name('edit');
        });
        Route::group(['middleware' => ['editor:3']], function () {
            Route::prefix('avatar')->name('avatar.')->group(function () {
                Route::any('/', 'PanelController@avatars')->name('default');
            });
        });
        Route::prefix('animes')->name('animes.')->group(function () {
            Route::match(['get', 'post'], '/', 'PanelController@animes')->name('default');
            Route::match(['get', 'post'], '/add', 'PanelController@animesAdd')->name('add');
            Route::prefix('edit')->name('edit.')->group(function () {
                Route::match(['get', 'post'], '/{slug}', 'PanelController@editAnime')->name('default');
                Route::match(['get', 'post'], '/{slug}/season/{season}', 'PanelController@editSeason')->name('season');
                Route::match(['get', 'post'], '/{slug}/season/{season}/episode/{episode}', 'PanelController@editEpisode')->name('episode');
            });
        });
    });
});
Route::get('/{anime_slug}', 'PagesController@anime')->name('anime.default');
Route::get('/{anime_slug}/{season}/episodio-{episode}/{episode_slug}', 'PagesController@episode')->name('anime.episode');

resources/views/watch/frame.blade.php
player = videojs ("video-player", {
        preload: true,
        controls: true,
        plugins: {
            videoJsResolutionSwitcher: {
                default: 'high',
                dynamicLabel: true
            }
        }
    }, function() {
        player.updateSrc([
        {
            src: '{{ $episode->video }}',
            type: 'video/mp4',
            label: '360'
        }
        ]);
    }
);

@if ($user != null)
var last = 0;
var start = 0;
function time_updated(time_update_event){
    var current_time = player.currentTime();
    var duration = player.duration();
    var time = Math.floor(current_time);

    if(time > duration || time_update_event.type === "ended") {
        time = 0;
    }
    if (last > 0 && (last == 500 || last % 500 == 0)) {
        var xhttp = new XMLHttpRequest();
        xhttp.open("POST", "{{ route('user.setEpisode') }}", true);
        xhttp.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
        xhttp.setRequestHeader('x-csrf-token', "{{ csrf_token() }}");
        xhttp.send("completed=false&anime_id={{ $episode->anime->id }}&season_id={{ $episode->season->id }}&episode_id={{ $episode->id }}&current_time=" + current_time + "&duration=" + duration);
        console.info('Source changed to % s', current_time);
        last = 0;
    } else if (time_update_event.type === "ended") {var xhttp = new XMLHttpRequest();
        xhttp.open("POST", "{{ route('user.setEpisode') }}", true);
        xhttp.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
        xhttp.setRequestHeader('x-csrf-token', "{{ csrf_token() }}");
        xhttp.send("completed=true&anime_id={{ $episode->anime->id }}&season_id={{ $episode->season->id }}&episode_id={{ $episode->id }}&current_time=" + current_time + "&duration=" + duration);
        console.info('Source changed to % s', current_time);
        last = 0;
    }
    last = last + 1;
}

player.on('loadedmetadata', time_updated);
player.on('timeupdate', time_updated);
player.on('ended', time_updated);
player.on('pause', time_updated);

@endif
player.hotkeys({
    volumeStep: 0.1,
    seekStep: 5,
    enableModifiersForNumbers: false
});
@if ($cache != null)
    @if ($cache->completed == 0)
        player.currentTime({{ $cache->current_time }});
    @endif
@endif

@if ($next != null)
player.suggestedVideoEndcap({
    header: ' &nbsp;Próximo Episódio',
    prev: "&nbsp;&nbsp;{{ $next->prev }}",
    episode: " &nbsp;{{ $next->title }}",
    url: '{{ route('anime.episode', ['anime_slug' => $next->season->anime->slug_name, 'episode' => $next->episode, 'episode_slug' => $next->slug, 'season' => $next->season_id]) }}',
    image: '{{ ZAnimesControl::url('animes/' . $next->image) }}',
});
@endif