routes/web.php
<?php

Route::get('/', 'PagesController@home')->name('home');
Route::get('/animes', 'PagesController@animes')->name('animes');
Route::get('/temporada', 'PagesController@season')->name('season');
Route::get('/dmca', 'PagesController@dmca')->name('dmca');
Route::get('/equipe', 'PagesController@dmca')->name('staff');
Route::any('/watch/{key}/{id}/{slug}', 'Controller@watch')->name('watch');


Route::get('/perfil/{name}', 'PagesController@perfil')->name('profile');

Route::group(['middleware' => ['guest']], function () {
    Route::post('/logar', 'AuthController@login')->name('login');
    Route::get('/cadastro', 'PagesController@register')->name('register');
    Route::post('/cadastro', 'AuthController@register');
});
Route::group(['middleware' => ['auth']], function () {
    Route::prefix('usuario')->name('user.')->group(function () {
        Route::post('/avatar', 'AuthController@avatar')->name('avatar');
        Route::post('/configuracoes', 'PagesController@settings')->name('settings');
        Route::post('/episode', 'Controller@setEpisode')->name('setEpisode');
        Route::get('/sair', function () {
            Auth::logout();
            Session::flush();
            return redirect('/');
        })->name('logout');
    });
});
Route::group(['middleware' => ['editor:1']], function () {
    Route::prefix('panel')->name('panel.')->group(function () {
        Route::get('/logs', 'PanelController@logs')->name('logs');
        Route::match(['get', 'post'], '/', 'PanelController@panel')->name('dashboard');
        Route::prefix('week')->name('week.')->group(function () {
            Route::get('/', 'PanelController@week')->name('default');
            Route::match(['get', 'post'], '/{week}', 'PanelController@weekEdit')->name('edit');
        });
        Route::group(['middleware' => ['editor:3']], function () {
            Route::prefix('avatar')->name('avatar.')->group(function () {
                Route::any('/', 'PanelController@avatars')->name('default');
            });
        });
        Route::prefix('animes')->name('animes.')->group(function () {
            Route::match(['get', 'post'], '/', 'PanelController@animes')->name('default');
            Route::match(['get', 'post'], '/add', 'PanelController@animesAdd')->name('add');
            Route::prefix('edit')->name('edit.')->group(function () {
                Route::match(['get', 'post'], '/{slug}', 'PanelController@editAnime')->name('default');
                Route::match(['get', 'post'], '/{slug}/season/{season}', 'PanelController@editSeason')->name('season');
                Route::match(['get', 'post'], '/{slug}/season/{season}/episode/{episode}', 'PanelController@editEpisode')->name('episode');
            });
        });
    });
});
Route::get('/{anime_slug}', 'PagesController@anime')->name('anime.default');
Route::get('/{anime_slug}/{season}/episodio-{episode}/{episode_slug}', 'PagesController@episode')->name('anime.episode');

resources/views/pages/anime.blade.php
@extends('layouts.pages_full')

@section('title', $anime->name)

@section('og_title', __('head.anime.og_title', ['anime' => $anime->name]))
@section('og_description', __('head.anime.og_description', ['anime' => $anime->name, 'description' => $anime->sinopse]))
@section('og_image', ZAnimesControl::url('animes/' . $anime->slug_name . '/' . $anime->image))

@section('header')
    <div class="c-search-header__wrapper">
        <div class="container">
            <div class="c-breadcrumb-wrapper">
                <div class="container">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item">
                                <a href="{{ route('home') }}">
                                    @lang('pages.menu.home')
                                </a>
                            </li>
                            <li class="breadcrumb-item"><a href="#">Anime</a></li>
                            <li class="breadcrumb-item active" aria-current="page">{{ $anime->name }}</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
@stop

@section('container')
    <div class="float-lg-right widget col-lg-4 default no-icon heading-style-1 c-popular">
        <div class="c-page__content">
            <div class="c-blog__heading style-2 font-heading">
                <h4>{{ $anime->name }}</h4>
            </div>
            <div class="widget-content">
                <div class="item-thumb">
                    <img data-src="{{ ZAnimesControl::url('animes/' . $anime->slug_name . '/' . $anime->image) }}" data-srcset="{{ ZAnimesControl::url('animes/' . $anime->slug_name . '/' . $anime->image) }}" data-sizes="(max-width: 125px) 100vw, 125px" class="img-fluid lazyload effect-fade" alt="{{ $anime->name }}"/>
                </div>
                <div class="manga-action">
                    <div class="add-bookmark">
                        <div class="action_icon">
                            <a href="#" data-action="bookmark" data-post="302" data-chapter="" data-page="" title="Bookmark">
                                <i class="ion ion-md-bookmark"></i></a></div><div class="action_detail">
                            <span>Bookmark This</span>
                        </div>
                    </div>
                    <div class="add-bookmark">
                        <div class="action_icon">
                            <a href="#" data-action="bookmark" data-post="302" data-chapter="" data-page="" title="Bookmark">
                                <i class="ion ion-md-bookmark"></i></a></div><div class="action_detail">
                            <span>Bookmark This</span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="manga-info">
                <h4>@lang('anime.info')</h4>
                <div class="item-summary">
                    <div class="post-content">
                        <div class="post-content_item">
                            <div class="summary-heading">
                                <h5>
                                    @lang('anime.author')
                                </h5>
                            </div>
                            <div class="summary-content">
                                {{ $anime->author }}
                            </div>
                        </div>
                        <div class="post-content_item">
                            <div class="summary-heading">
                                <h5>
                                    @lang('anime.status')
                                </h5>
                            </div>
                            <div class="summary-content">
                                @if ($anime->status == 1)
                                    @lang('anime.completed')
                                @else
                                    @lang('anime.on_going')
                                @endif
                            </div>
                        </div>
                        <div class="post-content_item">
                            <div class="summary-heading">
                                <h5>
                                    @lang('anime.year')
                                </h5>
                            </div>
                            <div class="summary-content">
                                {{ $anime->year }}
                            </div>
                        </div>
                        <div class="post-content_item">
                            <div class="summary-heading">
                                <h5>
                                    @lang('anime.studio')
                                </h5>
                            </div>
                            <div class="summary-content">
                                {{ $anime->studio }}
                            </div>
                        </div>
                        <div class="post-content_item">
                            <div class="summary-heading">
                                <h5>
                                    @lang('anime.age_group')
                                </h5>
                            </div>
                            <div class="summary-content">
                                {{ $anime->age_group }}
                            </div>
                        </div>
                        <div class="post-content_item">
                            <div class="summary-heading">
                                <h5>
                                    @lang('anime.uploader')
                                </h5>
                            </div>
                            <div class="summary-content">
                                <a href="{{ route('profile', ['name' => $anime->creator->name]) }}">{{ $anime->creator->name }}</a>
                            </div>
                        </div>
                        <div class="post-content_item">
                            <div class="summary-heading">
                                <h5>
                                    @lang('anime.genres')
                                </h5>
                            </div>
                            <div class="summary-content">
                                <div class="genres-content">
                                    @foreach($anime->genres as $genre)
                                        {{ $genre->name }}@if (!$loop->last), @endif
                                    @endforeach
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <h4>@lang('anime.about')</h4>
                <div class="description-summary">
                    {{ $anime->sinopse }}
                </div>
            </div>
        </div>
    </div>
    <div class="float-lg-left widget col-lg-8">
        <div class="style-1">
            <div class="c-blog__heading style-2 font-heading">
                <h4>@lang('anime.episodes')</h4>
            </div>
            <div class="widget-content">
                <div id="seasons">
                    <div class="listing-chapters_wrap">
                        <div class="main version-chap loaded episodes">
                            <div id="accordion">
                                @foreach($anime->seasons as $season)
                                    <div @if($anime->seasons->count() == 1 && $loop->first)style="display: none" @endif id="heading{{ $season->id }}">
                                        <h5 class="mb-0">
                                            <button class="btn btn-link menu" data-toggle="collapse" data-target="#collapse{{ $season->id }}" aria-expanded=" @if ($loop->first) true @else false @endif" aria-controls="collapse{{ $season->id }}">
                                                {{ $season->title }}
                                            </button>
                                        </h5>
                                    </div>

                                    <div id="collapse{{ $season->id }}" class="collapse @if ($loop->first) show @endif " aria-labelledby="heading{{ $season->id }}" data-parent="#accordion">
                                        <div class="col-md-12">
                                            <div class="row">
                                                @foreach($season->episodes as $episode)
                                                    <div class="col-md-3 episode">
                                                        <div class="anime">
                                                            <div class="episode">
                                                                <div class="data">
                                                                    <div class="thumb c-image-hover">
                                                                        <a href="{{ route('anime.episode', ['anime_slug' => $anime->slug_name, 'episode' => $episode->episode, 'episode_slug' => $episode->slug, 'season' => $episode->season_id]) }}">
                                                                            <img width="100px" height="60px" data-src="{{ ZAnimesControl::url('animes/' . $episode->image) }}" data-srcset="{{ ZAnimesControl::url('animes/' . $episode->image) }}"  class="img-fluid lazyload effect-fade" alt="{{ $episode->name }}"/>
                                                                            <div class="duration">{{ str_replace('00:', '', gmdate("H:i:s", $episode->duration)) }}</div>
                                                                        </a>
                                                                    </div>
                                                                    @auth
                                                                        <div class="episode_progress">
                                                                            <div class="ep_progress" style="width:{{ ZAnimesControl::porcentage($episode->current) }}%;"></div>
                                                                        </div>
                                                                    @endauth
                                                                    <h3>
                                                                        <a href="{{ route('anime.episode', ['anime_slug' => $episode->season->anime->slug_name, 'episode' => $episode->episode, 'episode_slug' => $episode->slug, 'season' => $episode->season_id]) }}">@lang('pages.episode'): {{ $episode->episode }}</a>
                                                                    </h3>
                                                                </div>

                                                                <div class="extra">
                                                                    <div class="name">{{ $episode->title }}</div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                @endforeach
                                            </div>
                                        </div>
                                    </div>
                                @endforeach
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="c-widget-wrap">
            <div class="popular-slider style-1 anims" data-style="style-1" data-count="4">
                <div class="c-blog__heading style-1 font-heading">
                    <h4>@lang('anime.also_liked')</h4>
                </div>
                <div class="slider__container" role="toolbar">
                    @foreach ($similar as $anim)
                        <div class="slider__item">
                            <div class="anime">
                                <a title="{{ $anim->title }}" href="{{ route('anime.default', ['anime_slug' => $anim->slug_name]) }}">
                                    <div class="poster">
                                        <img data-src="{{ ZAnimesControl::url('animes/' . $anim->slug_name . '/' . $anim->image) }}" data-srcset="{{ ZAnimesControl::url('animes/' . $anim->slug_name . '/' . $anim->image) }}" data-sizes="(max-width: 125px) 100vw, 125px" class="img-responsive lazyload" alt="{{ $anim->name }}"/>
                                    </div>
                                    <div class="info">
                                        <div class="title">{{ $anim->name }}</div>
                                        <div class="eps">@lang('home.episodes', ['count' => $anim->episodes->count()])</div>
                                    </div>
                                </a>
                            </div>
                        </div>
                    @endforeach
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/pages/dmca.blade.php
@extends('layouts.pages_full')

@section('title', 'DMCA')

@section('header')
    <div class="c-search-header__wrapper">
        <div class="container">
            <div class="c-breadcrumb-wrapper">
                <div class="container">
                    <div class="col-md-12">
                        <div class="c-breadcrumb">
                            <ol class="breadcrumb">
                                <li>
                                    <a href="{{ route('home') }}">
                                        @lang('pages.menu.home')
                                    </a>
                                </li>
                                <li class="active">
                                    DMCA
                                </li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

@section('container')
    <div class="widget col-md-12">
        <div class="c-widget-wrap">
            <div class="c-blog__heading style-2 font-heading">
                <h4>
                    DMCA
                </h4>
            </div>
            <div class="tab-content-wrap">

                zanimes.com implements the following DMCA Notice and Takedown Policy. ZAnimes respects the intellectual property rights of third parties, and expects others to do the same. As part of our effort to recognize the copyrights of third parties, ZAnimes complies with the U.S. Digital Millennium Copyright Act ("DMCA") and is therefore protected by the limitations on liability recognized by 47 U.S.C. § 512; commonly known as the "safe harbor" provisions of the DMCA.

                <h2 style="font-size:16px;">Notification</h2>

                We take abuse of our service very seriously. If you wish to report a copyright infringement, we need you to send us a proper notification.
                <br>
                A proper notification MUST have at least the following information, or it may be IGNORED:
                <br>
                <br>
                1. Identify yourself as either:
                <br>
                <br>
                - The owner of a copyrighted work(s), or
                <br>
                - A person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.
                <br>
                2. State your contact information, including your TRUE NAME, street address, telephone number, and email address.
                <br>
                3. Identify the copyrighted work that you believe is being infringed, or if a large number of works are appearing at a single website, a representative list of the works.
                <br>
                4. Identify the material that you claim is infringing your copyrighted work, to which you are requesting that FreakShare disable access over the World Wide Web.
                <br>
                5. Identify the location of the material on the World Wide Web by providing information reasonably sufficient to permit FreakShare to locate the material.
                <br>
                6. State that you have a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agents, or the law.
                <br>
                7. State that the information in the notice is accurate, under penalty of perjury.
                <br>
                <br>
                Claimants may send their Notice of Claimed Infringement to:
                <br>
                <br>
                DMCA Complaints
                <br>
                zanimes.com
                <br>
                <h4>Email: contact@zanimes.com</h4>
                <br>
                Please do not send other inquires or information to our Designated Agent.
                <br>
                All claims of copyright infringement on or regarding this website should be delivered ONLY to ZAnimes designated copyright agents.
            </div>
        </div>
    </div>
@stop

resources/views/pages/login.blade.php
@extends('layouts.auth')

@section('title', __('pages.register-title'))

@section('container')
    <div class="panel-form" id="form-login">
        <div class="modal-dialog" role="document">
            <div class="panel-content">
                <div class="modal-body">
                    <div id="login" class="login">
                        <h1>
                            @lang('login.title')
                        </h1>
                        @if ($errors->any())
                            @foreach($errors->all() as $message)
                                <div class="alert alert-danger" role="danger">
                                    {{ $message }}
                                </div>
                            @endforeach
                        @endif
                        <form name="login" method="post">
                            @csrf
                            <p>
                                <label>@lang('login.email')<br>
                                    <input type="email" name="email" class="input user_login" value="" size="20">
                                </label>
                            </p>
                            <p>
                                <label>@lang('login.password')<br>
                                    <input type="password" name="password" class="input user_login" value="" size="20">
                                </label>
                            </p>
                            <p class="forgetmenot">
                                <label>
                                    <input name="rememberme" type="checkbox" id="rememberme" value="forever">Remember Me
                                </label>
                            </p>
                            <p class="submit">
                                <input type="submit" name="wp-submit" class="button button-primary button-large wp-submit" value="@lang('login.submit')">
                            </p>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/pages/perfil.blade.php
@extends('layouts.pages_full')

@section('title', $user->name)


@section('header')
    <div class="profile">
        <div class="page-listing-item shortcode-manga-chapter">
            <div class="container">
                <div class="col-md-12">
                    <div class="wall">
                        <div class="avatar">
                            <div class="image">
                                @if($me)
                                    <img width="120" height="120" src="{{ ZAnimesControl::url('avatars/default.jpg') }}" srcset="{{ $user->avatar_pending }}" data-src="{{ $user->avatar_pending }}" data-srcset="{{ $user->avatar_pending }}" height="50" width="50">
                                @else
                                    <img width="120" height="120" src="{{ ZAnimesControl::url('avatars/default.jpg') }}" srcset="{{ $user->avatar }}" data-src="{{ $user->avatar }}" data-srcset="{{ $user->avatar }}" height="50" width="50">
                                @endif
                            </div>
                        </div>
                        @if($me)
                        <div class="menu">
                            <a data-toggle="modal" data-target="#avatarModel" href="#">
                                <div class="button">@lang('profile.avatar.change') <i class="ion ion-md-camera"></i></div>
                            </a>
                            <a data-toggle="modal" data-target="#avatarModel" href="#">
                                <div class="button">@lang('profile.wall.change') <i class="ion ion-md-image"></i></div>
                            </a>
                        </div>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
    @if($me)
        <!-- Modal -->
        <div class="modal fade" id="avatarModel" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">@lang('profile.avatar.title')</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>

                    <form action="{{ route('user.avatar') }}" method="post" enctype="multipart/form-data">
                        <div class="modal-body">
                            @csrf
                            <div class="form-group">
                                <div id="image-container">
                                    <img src="http://cdn.zanimes.com/avatars/default.jpg">
                                </div>
                            </div>
                            <div class="form-group">
                                <input type="file" name="image" id="image-file" />
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="submit" class="btn btn-primary">@lang('profile.avatar.save')</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    @endif
@stop

@section('container')
    @if ($me && $user->avatar_pending != $user->avatar)
    <div class="widget col-md-12">
        <div class="alert alert-warning" role="warning">
            <p>@lang('profile.avatar.pending')</p>
        </div>
    </div>
    @endif
    @if ($user->editor)
    <div class="widget col-md-12">
        <div class="row">
            <div class="widget col-md-8">
                <div class="c-widget-wrap">
                    <div class="popular-slider style-1 anims" data-style="style-3" data-count="4">
                        <div class="c-blog__heading style-2 font-heading">
                            <h4>@lang('profile.animes_posted')</h4>
                        </div>
                        <div class="slider__container" role="toolbar">
                            @foreach ($user->animes()->limit(15)->get() as $latest)
                                <div class="slider__item">
                                    <div class="anime">
                                        <a title="{{ $latest->title }}" href="{{ route('anime.default', ['anime_slug' => $latest->slug_name]) }}">
                                            <div class="poster">
                                                <img data-src="{{ ZAnimesControl::url('animes/' . $latest->slug_name . '/' . $latest->image) }}" data-srcset="{{ ZAnimesControl::url('animes/' . $latest->slug_name . '/' . $latest->image) }}" data-sizes="(max-width: 125px) 100vw, 125px" class="img-responsive lazyload" alt="{{ $latest->name }}"/>
                                            </div>
                                            <div class="info">
                                                <div class="title">{{ $latest->name }}</div>
                                                <div class="eps">@lang('home.episodes', ['count' => $latest->episodes->count()])</div>
                                            </div>
                                        </a>
                                    </div>
                                </div>
                            @endforeach
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @endif

@stop

@section('footer')
    <script src="{{ asset('crop/jquery.js') }}"></script>
    <script src="{{ asset('crop/default.js') }}"></script>
@stop

resources/views/pages/register.blade.php
@extends('layouts.auth')

@section('title', __('pages.register-title'))

@section('container')
    <div class="panel-form" id="form-login">
        <div class="modal-dialog" role="document">
            <div class="panel-content">
                <div class="modal-body">
                    <div id="login" class="login">
                        <h1>
                            @lang('pages.register-title')
                        </h1>
                        @if ($errors->any())
                            @foreach($errors->all() as $message)
                                <div class="alert alert-danger" role="danger">
                                    {{ $message }}
                                </div>
                            @endforeach
                        @endif
                        <form name="register" method="post">
                            @csrf
                            <p>
                                <label>@lang('pages.register-name')<br>
                                    <input type="text" name="username" class="input user_login" value="" size="20">
                                </label>
                            </p>
                            <p>
                                <label>@lang('pages.register-email')<br>
                                    <input type="email" name="email" class="input user_login" value="" size="20">
                                </label>
                            </p>
                            <p>
                                <label>@lang('pages.register-password')<br>
                                    <input type="password" name="password" class="input user_login" value="" size="20">
                                </label>
                            </p>
                            <p>
                                <label>@lang('pages.register-r-password')<br>
                                    <input type="password" name="r_password" class="input user_login" value="" size="20">
                                </label>
                            </p>
                            <p class="submit">
                                <input type="submit" name="wp-submit" class="button button-primary button-large wp-submit" value="@lang('pages.register-submit')">
                            </p>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop